name: "Determine Fedora versions"
description: "Determine the latest and previous versions of Fedora to run the CI against"
inputs:
  test-override:
    description: 'Override matrix for testing'
    required: true
outputs:
  matrix: 
    description: "Fedora versions"
    value: ${{ steps.set-matrix.outputs.matrix }}
runs:
  using: "composite"
  steps:
    - id: set-matrix
      run: |
        export latest=$(cat /etc/fedora-release | awk '{ print $3 }')
        export previous=$(cat /etc/fedora-release | awk '{ print $3 - 1}')
        echo "Running CI against Fedora $previous and $latest"
        if [ "${{ secrets.MATRIX }}" == "" ]
        then
          echo "::set-output name=matrix::{\"os\":[\"$previous\", \"$latest\"]}"
        else
          echo "::set-output name=matrix::${{ secrets.MATRIX }}"
        fi
        echo "::set-output name=matrix::{\"os\":[\"$previous\", \"$latest\"]}"
      shell: bash
