name: "Determine Fedora versions"
description: "Determine the latest and previous versions of Fedora to run the CI against"
outputs:
  matrix: 
    description: "Fedora versions"
    value: ${{ steps.set-matrix.outputs.matrix }}
runs:
  using: "composite"
  steps:
    - id: set-matrix
      run: |
        export latest=$(cat /etc/fedora-release | awk '{ print $3 }')
        export previous=$(cat /etc/fedora-release | awk '{ print $3 - 1}')
        if [ "${{ secrets.MATRIX }}" == "" ]
        then
          echo "::set-output name=matrix::{\"os\":[\"$previous\", \"$latest\"]}"
          echo "Running CI against Fedora $previous and $latest"
        else
          echo "::set-output name=matrix::${{ secrets.MATRIX }}"
          echo "Test matrix defined: ${{ secrets.MATRIX }}"
        fi
      shell: bash
